#!/usr/bin/env python3
"""gh_board.py — GitHub Projects board management (identity from board_config.json).

Usage (from repo root):
  python3 .zcode/scripts/gh_board.py pick-next [host]           — token for auto-impl watcher: NONE | <issue>; per-host budget host_budgets[host]
  python3 .zcode/scripts/gh_board.py host N                     — the card's host field value (watcher tiebreak token)
  python3 .zcode/scripts/gh_board.py reconcile [host] [--dry-run] — watcher-side stale-card sweep: closed issue in In IMPL/PR (G7) → In-main/Not planned; dead In IMPL run on this host → Ready to IMPL + BLOCKED auto-log entry
  python3 .zcode/scripts/gh_board.py pick-next-design            — token for design kickoff: <issue> | NONE (reason)
  python3 .zcode/scripts/gh_board.py auto-log N "BLOCKED ..."    — append an entry to the issue's auto-impl log comment
  python3 .zcode/scripts/gh_board.py auto-state N                — last auto-impl log entry (or nothing)
  python3 .zcode/scripts/gh_board.py show N                      — read one card: status, host, gate
  python3 .zcode/scripts/gh_board.py show all                    — the whole board as a table
  python3 .zcode/scripts/gh_board.py status N "In IMPL" [host]  — move a card; entering In IMPL/In Design stamps the host field, leaving clears it (host survives PR (G7), clears on leaving it)
  python3 .zcode/scripts/gh_board.py gate N concept|spec|plan|blocked|none — the pending-ask marker: a design gate stop or an IMPL blocker awaiting the user
  python3 .zcode/scripts/gh_board.py merged N PR ["short title"] — append the "Recently merged" line (scratchpad v2)
  python3 .zcode/scripts/gh_board.py issue N                      — standard issue view: state, labels, body

Project identity is NOT hardcoded: the project node id + number, owner,
repo, custom-field ids and per-host budgets come from
docs/board/board_config.json (format v1, generated by board_bootstrap.py
adopt — issue #24; never hand-set). Repo root is resolved from the
script's own path (parents[2]), so both twins read the same file.
Card ownership lives in the single-select field "host" (options: imac,
macbook, hk, gcp): claiming is a field write and the race tiebreak re-reads
the field. This replaced the CLAIM-comment mechanism; the auto-impl log
comment remains the BLOCKED channel only.
The pending-ask marker lives in the single-select field "gate" (options:
concept, spec, plan, blocked): a design session stamps it at a gate stop,
an IMPL manager stamps "blocked" when a blocker awaits the user; it is
emptied at the user's answer and automatically when the card leaves
In IMPL/In Design. It replaced the gate:* issue labels.
Statuses and option ids are read live from the board (the option list is
user-managed in the web UI — never hardcode).
The script is part of the host/container seam and travels via git.
Identical copies ship in BOTH harness folders — .zcode/scripts/ (host)
and .opencode/scripts/ (container); when editing, change both (or edit
one and copy over).
"""
import json
import os
import re
import sqlite3
import subprocess
import sys
from datetime import date, datetime, timezone
from pathlib import Path

SCRATCHPAD = Path(__file__).resolve().parents[2] / ".opencode" / "scratchpad.md"
MERGED_BLOCK = "## Recently merged"
MERGED_MAX = 5
SESSION_DB = Path("/root/.local/share/opencode/opencode.db")  # container-side session store (liveness source for reconcile)
SESSION_IDLE_LIMIT_S = 3600  # a run's sessions silent this long = stuck (the 2026-09-22 #319 dead-stream incident)

# Board identity is NOT hardcoded: project node id + number, owner, repo,
# custom-field ids and per-host budgets live in docs/board/board_config.json
# (format v1, generated by board_bootstrap.py adopt — issue #24). Loaded
# lazily by load_config() before any command touches the network; validated
# fully offline (a corrupted or redirected config must fail before any board
# mutation runs). The script is byte-identical across repos; only the
# config is per-repo.
REPO_ROOT = Path(__file__).resolve().parents[2]  # identical for both twins (the parents[2] convention)
BOARD_CONFIG_PATH = REPO_ROOT / "docs" / "board" / "board_config.json"
REQUIRED_CONFIG_KEYS = ("version", "project_id", "project_number", "owner", "repo", "fields", "host_budgets")
_OWNER_RE = re.compile(r"^[A-Za-z0-9](?:[A-Za-z0-9-]{0,37}[A-Za-z0-9])?$")  # GitHub login charset
_REPO_RE = re.compile(r"^[A-Za-z0-9._-]+$")  # GitHub repo name charset
_PVT_RE = re.compile(r"^PVT_[A-Za-z0-9_-]+$")  # project node id
_PVTSSF_RE = re.compile(r"^PVTSSF_[A-Za-z0-9_-]+$")  # single-select field node id

PROJECT_ID: str | None = None
OWNER: str | None = None
REPO: str | None = None
PROJECT_NUM: int | None = None
HOST_BUDGETS: dict[str, int] = {}
_CONFIG: dict | None = None

# Statuses are read live from the board (the option list is user-managed in
# the web UI — e.g. "Not planned" was added there 2026-09-09; never hardcode).

_status_field_id = None
_status_opts = None
_host_field_id = None
_host_field_opts = None
_gate_field_id = None
_gate_field_opts = None


def gql(query: str) -> dict:
    r = subprocess.run(
        ["gh", "api", "graphql", "-f", f"query={query}"],
        capture_output=True, text=True,
    )
    if r.returncode != 0:
        sys.exit(f"gh api error: {r.stderr.strip()}")
    data = json.loads(r.stdout)
    if "errors" in data:
        sys.exit(f"graphql errors: {data['errors']}")
    return data["data"]


def load_config(force: bool = False) -> dict:
    """Load and validate docs/board/board_config.json (format v1 — the
    single source of project identity, written by board_bootstrap.py adopt,
    issue #24) into the module globals. All checks run BEFORE any network
    call: missing file, wrong version, garbage JSON, a missing required key
    and malformed values (owner/repo charset, PVT…/PVTSSF… node-id patterns)
    each exit cleanly with the reason. Cached; force=True re-reads."""
    global _CONFIG, PROJECT_ID, OWNER, REPO, PROJECT_NUM, HOST_BUDGETS
    if _CONFIG is not None and not force:
        return _CONFIG
    path = BOARD_CONFIG_PATH
    if not path.is_file():
        sys.exit(f"board config not found: {path}\n"
                 "run: board_bootstrap.py adopt <project-number> — it generates the config (issue #24)")
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except ValueError as e:
        sys.exit(f"board config {path}: invalid JSON: {e}")
    if not isinstance(data, dict):
        sys.exit(f"board config {path}: invalid JSON: expected an object")
    for key in REQUIRED_CONFIG_KEYS:
        if key not in data:
            sys.exit(f"board config {path}: missing required key '{key}'")
    if isinstance(data["version"], bool) or data["version"] != 1:
        sys.exit(f"board config {path}: unsupported version {data['version']!r} — expected 1")
    pn = data["project_number"]
    if not isinstance(pn, int) or isinstance(pn, bool):
        sys.exit(f"board config {path}: 'project_number' must be an integer, got {pn!r}")
    owner, repo = data["owner"], data["repo"]
    if not isinstance(owner, str) or not _OWNER_RE.fullmatch(owner):
        sys.exit(f"board config {path}: invalid owner {owner!r} — must match the GitHub login charset "
                 "(alphanumerics, single hyphens, no leading/trailing hyphen)")
    if not isinstance(repo, str) or not _REPO_RE.fullmatch(repo):
        sys.exit(f"board config {path}: invalid repo {repo!r} — must match the GitHub repo name charset "
                 "(alphanumerics, hyphens, underscores, dots)")
    pid = data["project_id"]
    if not isinstance(pid, str) or not _PVT_RE.fullmatch(pid):
        sys.exit(f"board config {path}: invalid project_id {pid!r} — expected a PVT_… node id")
    fields = data["fields"]
    if not isinstance(fields, dict) or not all(
            isinstance(k, str) and isinstance(v, str) and _PVTSSF_RE.fullmatch(v)
            for k, v in fields.items()):
        sys.exit(f"board config {path}: 'fields' must map field name → PVTSSF_… node id")
    budgets = data["host_budgets"]
    if not isinstance(budgets, dict) or not all(
            isinstance(k, str) and isinstance(v, int) and not isinstance(v, bool)
            for k, v in budgets.items()):
        sys.exit(f"board config {path}: 'host_budgets' must map host name → integer budget")
    _CONFIG = data
    PROJECT_ID, OWNER, REPO, PROJECT_NUM, HOST_BUDGETS = pid, owner, repo, pn, budgets
    return _CONFIG


def _config_field_id(cfg: dict, name: str) -> str:
    fid = cfg["fields"].get(name)
    if not fid:
        sys.exit(f"board config {BOARD_CONFIG_PATH}: fields missing '{name}' — regenerate with board_bootstrap.py adopt")
    return fid


def load_status_field():
    """Field ids come from board_config.json; the Status/host/gate OPTION
    ids are read live from the project (the option list is user-managed in
    the web UI — never hardcode). The field-list read exits loudly on page
    overflow — a truncated list must never silently miss a field."""
    global _status_field_id, _status_opts, _host_field_id, _host_field_opts, _gate_field_id, _gate_field_opts
    if _status_field_id:
        return
    cfg = load_config()
    d = gql(f'query {{ node(id: "{PROJECT_ID}") {{ ... on ProjectV2 {{ fields(first: 30) {{ pageInfo {{ hasNextPage }} nodes {{ __typename ... on ProjectV2SingleSelectField {{ id name options {{ id name }} }} }} }} }} }} }}')
    page = d["node"]["fields"]
    if page["pageInfo"]["hasNextPage"]:
        sys.exit(f"project {PROJECT_NUM} has more than 30 fields — the field list would be truncated, refusing to guess option ids")
    for f in page["nodes"]:
        if f["__typename"] != "ProjectV2SingleSelectField":
            continue
        if f["name"] == "Status":
            _status_opts = {o["name"]: o["id"] for o in f["options"]}
        elif f["name"] == HOST_FIELD_NAME:
            _host_field_opts = {o["name"]: o["id"] for o in f["options"]}
        elif f["name"] == GATE_FIELD_NAME:
            _gate_field_opts = {o["name"]: o["id"] for o in f["options"]}
    if not _status_opts:
        sys.exit("Status field not found")
    if not _host_field_opts:
        sys.exit(f"'{HOST_FIELD_NAME}' single-select field not found — create it on the project (options: imac, macbook, hk, gcp)")
    if not _gate_field_opts:
        sys.exit(f"'{GATE_FIELD_NAME}' single-select field not found — create it on the project (options: concept, spec, plan, blocked)")
    _status_field_id = _config_field_id(cfg, "Status")
    _host_field_id = _config_field_id(cfg, HOST_FIELD_NAME)
    _gate_field_id = _config_field_id(cfg, GATE_FIELD_NAME)


def items_with_fields() -> list[dict]:
    out = []
    cursor = ""
    while True:
        after = f', after: "{cursor}"' if cursor else ""
        d = gql(f'''query {{ node(id: "{PROJECT_ID}") {{ ... on ProjectV2 {{ items(first: 50{after}) {{ pageInfo {{ hasNextPage endCursor }} nodes {{
            id
            content {{ ... on Issue {{ number title state }} }}
            fieldValues(first: 20) {{ nodes {{
                ... on ProjectV2ItemFieldSingleSelectValue {{ name field {{ ... on ProjectV2FieldCommon {{ name }} }} }}
            }} }}
        }} }} }} }} }}''')
        page = d["node"]["items"]
        for it in page["nodes"]:
            c = it.get("content")
            if not c or "number" not in c:
                continue
            vals = {v["field"]["name"]: v["name"] for v in it["fieldValues"]["nodes"] if v}
            out.append({
                "item_id": it["id"],
                "number": c["number"],
                "title": c["title"],
                "state": c["state"],
                "status": vals.get("Status"),
                "priority": vals.get("Priority"),
                "host": vals.get(HOST_FIELD_NAME),
                "gate": vals.get(GATE_FIELD_NAME),
            })
        if not page["pageInfo"]["hasNextPage"]:
            break
        cursor = page["pageInfo"]["endCursor"]
    return out


def find_item(number: int) -> dict:
    for it in items_with_fields():
        if it["number"] == number:
            return it
    # not on the board — add it
    d = gql(f'query {{ repository(owner: "{OWNER}", name: "{REPO}") {{ issue(number: {number}) {{ id title state }} }} }}')
    issue = d["repository"]["issue"]
    if not issue:
        sys.exit(f"Issue #{number} not found")
    d2 = gql(f'mutation {{ addProjectV2ItemById(input: {{ projectId: "{PROJECT_ID}", contentId: "{issue["id"]}" }}) {{ item {{ id }} }} }}')
    return {
        "item_id": d2["addProjectV2ItemById"]["item"]["id"],
        "number": number, "title": issue["title"], "state": issue["state"],
        "status": None, "priority": None, "host": None, "gate": None,
    }


def set_field(item_id: str, field_id: str, option_id: str | None):
    value = f'value: {{ singleSelectOptionId: "{option_id}" }}' if option_id else "value: {}"
    # clearing a single-select — an empty value is not supported; use the clear mutation
    if option_id is None:
        gql(f'mutation {{ clearProjectV2ItemFieldValue(input: {{ projectId: "{PROJECT_ID}", itemId: "{item_id}", fieldId: "{field_id}" }}) {{ projectV2Item {{ id }} }} }}')
    else:
        gql(f'mutation {{ updateProjectV2ItemFieldValue(input: {{ projectId: "{PROJECT_ID}", itemId: "{item_id}", fieldId: "{field_id}", {value} }}) {{ projectV2Item {{ id }} }} }}')


CLAIM_TTL_HOURS = 1  # auto-impl: freshness of claim/blocked log entries — a fresh entry means the card is in flight or resting
DEFAULT_HOST_BUDGET = 1  # unknown hosts (hk, gcp — reserved) get one slot; per-host budgets live in board_config.json (host_budgets)
HOST_FIELD_NAME = "host"  # single-select ownership field; options imac/macbook/hk/gcp
GATE_FIELD_NAME = "gate"  # single-select pending-ask field; options concept/spec/plan/blocked (replaced the gate:* issue labels 2026-09-20)
PRIORITY_RANK = {"critical": 0, "high": 1, "medium": 2, "low": 3}  # pick ordering: Critical first, unset last, ties by issue number
AUTO_IMPL_LOG_PREFIX = "auto-impl log:"
_LOG_PIN: dict[int, int] = {}  # issue number → canonical auto-impl log comment id (pinned at creation by cmd_auto_log)
_DEP_RE = re.compile(r"(?im)^\s*depends-on:\s*(.+)$")
_NUM_RE = re.compile(r"#(\d+)")


def _priority_key(it: dict) -> tuple[int, int]:
    """Pick ordering key (priority first, then the older issue number):
    rank Critical=0, High=1, Medium=2, Low=3, unset=4. Priority NEVER
    overrides status eligibility — callers filter candidates by status
    prefix first; the key only orders within an eligibility class."""
    p = (it.get("priority") or "").strip().lower()
    return (PRIORITY_RANK.get(p, 4), it["number"])


def _open_deps(number: int) -> list[int]:
    """Issue numbers from body lines `depends-on: #12, #34` that are still OPEN.
    Convention for the auto-impl pipeline: declare hard dependencies in the
    issue body so the watcher can skip not-yet-mergeable cards cheaply."""
    r = subprocess.run(
        ["gh", "issue", "view", str(number), "--json", "body",
         "--repo", f"{OWNER}/{REPO}"],
        capture_output=True, text=True,
    )
    if r.returncode != 0:
        return []
    body = json.loads(r.stdout or "{}").get("body") or ""
    nums: list[int] = []
    for m in _DEP_RE.finditer(body):
        nums += [int(n) for n in _NUM_RE.findall(m.group(1))]
    open_deps = []
    for n in dict.fromkeys(nums):
        try:
            d = gql(f'query {{ repository(owner: "{OWNER}", name: "{REPO}") {{ issue(number: {n}) {{ state }} }} }}')
            issue = d["repository"]["issue"]
        except SystemExit:
            # Deleted/nonexistent issue number (e.g. stray digits in the line):
            # not a dependency — skip it instead of blinding the whole picker.
            continue
        if issue and issue["state"] == "OPEN":
            open_deps.append(n)
    return open_deps


def _resolve_host(explicit: str | None = None) -> str | None:
    """Which machine this invocation acts for: an explicit arg wins, then the
    GH_BOARD_HOST env (set by the watcher), then the container's host-label
    file (covers manual manager runs inside the container). None = unresolved."""
    if explicit:
        return explicit.strip().lower()
    env = os.environ.get("GH_BOARD_HOST", "").strip()
    if env:
        return env.lower()
    label = Path("/root/.local/state/opencode/auto-impl-host")
    try:
        if label.is_file():
            return label.read_text().strip().lower() or None
    except OSError:
        pass
    return None


def cmd_pick_next(host_arg: str | None = None):
    """Token protocol for .opencode/scripts/auto_impl_watch.sh: NONE | <number>.
    Candidates: OPEN issues with board status "Ready to IMPL".
    Order: priority (Critical > High > Medium > Low, unset last), then the
    lower (older) issue number. Priority never overrides status eligibility.
    Skipped: cards whose auto-impl log comment's LAST entry is a fresh
    (<= CLAIM_TTL_HOURS) CLAIM/BLOCKED, and cards whose body declares
    `depends-on: #N` with N still OPEN.
    Budget: PER-HOST — cards "In IMPL" whose host field names this machine
    count against host_budgets[host] (board_config.json). In IMPL cards with
    an empty host block no one (stderr warning) — ownership lives in the
    field, there is no comment fallback. Manual IMPL sessions count too:
    they stamp the host via the label file."""
    host = _resolve_host(host_arg)
    if not host:
        sys.exit("pick-next needs a host: pass it as an argument or set GH_BOARD_HOST")
    load_status_field()
    items = [it for it in items_with_fields() if it["state"] == "OPEN"]
    in_impl = [it for it in items if (it["status"] or "").lower() == "in impl"]
    orphans = [f"#{it['number']}" for it in in_impl if not it["host"]]
    if orphans:
        print(f"warn: In IMPL cards without host (blocking no one): {', '.join(orphans)}", file=sys.stderr)
    mine = sum(1 for it in in_impl if (it["host"] or "") == host)
    if mine >= HOST_BUDGETS.get(host, DEFAULT_HOST_BUDGET):
        print("NONE")
        return
    # the board status is "Ready to IMPL": prefix match, not exact string
    ready = [it for it in items if (it["status"] or "").startswith("Ready to IMPL")]
    ready.sort(key=_priority_key)
    for it in ready:
        _, log_body = _auto_impl_log(it["number"])
        if log_body:
            entries = [ln[2:] for ln in log_body.splitlines() if ln.startswith("- ")]
            if entries:
                m2 = re.match(r"(\S+)\s+(\w+)", entries[-1])
                if m2:
                    try:
                        ts = datetime.fromisoformat(m2.group(1).replace("Z", "+00:00"))
                        fresh = (datetime.now(timezone.utc) - ts).total_seconds() <= CLAIM_TTL_HOURS * 3600
                        if fresh and m2.group(2) in ("CLAIM", "BLOCKED"):
                            continue
                    except ValueError:
                        pass
        if _open_deps(it["number"]):
            continue
        print(it["number"])
        return
    print("NONE")


def cmd_pick_next_design():
    """Token protocol for the DESIGN phase kickoff: <number> | NONE (reason).
    Capacity invariant: if ANY board card sits in a status starting with
    "In Design", nothing new enters design (one design at a time).
    Candidates: OPEN issues with board status starting with "Backlog".
    Skipped: cards whose body declares `depends-on: #N` with N still OPEN.
    Order: priority (Critical > High > Medium > Low, unset last), then the
    lower (older) issue number. Priority never overrides status eligibility."""
    load_config()
    all_items = items_with_fields()
    # capacity invariant: the design slot is busy — take no new cards
    busy = [f"#{it['number']}" for it in all_items
            if (it["status"] or "").startswith("In Design")]
    if busy:
        print(f"NONE (design slot busy: {', '.join(busy)})")
        return
    # the board status is "Backlog": prefix match, not exact string
    backlog = [it for it in all_items
               if it["state"] == "OPEN" and (it["status"] or "").startswith("Backlog")]
    if not backlog:
        print("NONE (no Backlog cards)")
        return
    backlog.sort(key=_priority_key)
    for it in backlog:
        if _open_deps(it["number"]):
            continue
        print(it["number"])
        return
    print("NONE (all Backlog cards blocked by depends-on)")


def _auto_impl_log(number: int):
    """The watcher's single log comment (starts with AUTO_IMPL_LOG_PREFIX)
    → (comment_id, body) or (None, None). Entries are "- <iso-ts> <text>"
    lines appended chronologically at the bottom.
    Canonical-comment pinning (spoof resistance — anyone who can comment
    could otherwise forge or shadow the log): the id pinned at creation
    (_LOG_PIN) wins while that comment still exists; a cold scan takes the
    OLDEST prefix-matching comment authored by the repo owner and pins it —
    later prefix matches (e.g. from another author) are never the log.
    Fetched via REST: the id must be numeric — `gh issue view --json comments`
    (gh ≥ 2.100) returns GraphQL node ids, and REST PATCH 404s on them."""
    r = subprocess.run(
        ["gh", "api", f"repos/{OWNER}/{REPO}/issues/{number}/comments"],
        capture_output=True, text=True,
    )
    if r.returncode != 0:
        return None, None
    comments = json.loads(r.stdout or "[]")
    pin = _LOG_PIN.get(number)
    if pin is not None:
        for c in comments:
            if c.get("id") == pin:
                return c["id"], c.get("body", "")
    for c in comments:
        if c.get("body", "").startswith(AUTO_IMPL_LOG_PREFIX) \
                and (c.get("user") or {}).get("login") == OWNER:
            _LOG_PIN[number] = c["id"]
            return c["id"], c.get("body", "")
    return None, None


def cmd_auto_log(number: int, entry: str):
    """Append "<now> <entry>" to the auto-impl log comment (create if missing).
    Read-merge-append: the body is re-fetched right before the patch, so a
    concurrent appender's lines are kept (last writer wins the merge).
    On creation the new comment's id is pinned as the canonical log id
    (_LOG_PIN) — later prefix-matching comments from other authors are then
    ignored by _auto_impl_log."""
    load_config()
    line = f"- {datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')} {entry}"
    cid, body = _auto_impl_log(number)
    if cid is None:
        r = subprocess.run(
            ["gh", "issue", "comment", str(number), "--body", f"{AUTO_IMPL_LOG_PREFIX}\n{line}",
             "--repo", f"{OWNER}/{REPO}"], capture_output=True, text=True)
        if r.returncode != 0:
            sys.exit(f"auto-log create failed: {r.stderr.strip()}")
        m = re.search(r"#issuecomment-(\d+)", r.stdout or "")
        if m:
            _LOG_PIN[number] = int(m.group(1))
        print("log created")
        return
    _LOG_PIN[number] = cid
    new_body = body.rstrip("\n") + "\n" + line
    r = subprocess.run(
        ["gh", "api", "-X", "PATCH", f"repos/{OWNER}/{REPO}/issues/comments/{cid}",
         "-f", f"body={new_body}"], capture_output=True, text=True)
    if r.returncode != 0:
        sys.exit(f"auto-log append failed: {r.stderr.strip()}")
    print("log appended")


def cmd_auto_state(number: int):
    """Last line of the auto-impl log ("<ts> <entry>") or nothing.
    Diagnostics for humans; since 2026-09-20 the claim tiebreak reads the
    host field (cmd_host), not this log."""
    load_config()
    _, body = _auto_impl_log(number)
    if not body:
        return
    entries = [ln[2:] for ln in body.splitlines() if ln.startswith("- ")]
    if entries:
        print(entries[-1])


def cmd_host(number: int):
    """The card's host field value (token protocol for the watcher tiebreak):
    prints the option name, or nothing when the card has no host."""
    load_config()
    for it in items_with_fields():
        if it["number"] == number:
            if it["host"]:
                print(it["host"])
            return
    sys.exit(f"#{number} is not on the board")


def _impl_run_alive(number: int) -> bool | None:
    """Is some `opencode run` process carrying this issue in its cmdline (the
    `--title "#N IMPL.…"` or a «продолжаем траекторию #N» prompt) alive on THIS
    machine? Fallback liveness for the "no session rows yet" window (a launch
    just happened, or the claim was orphaned). /proc-based — None when /proc
    is absent (a macOS host run)."""
    proc = Path("/proc")
    if not proc.is_dir():
        return None
    needle = f"#{number}".encode()
    for p in proc.glob("[0-9]*"):
        try:
            cmdline = (p / "cmdline").read_bytes()
        except OSError:
            continue
        if needle in cmdline:
            return True
    return False


def _run_session_fresh(number: int) -> bool | None:
    """Is work on this card still alive server-side? The `opencode run` CLI is
    only an attach client — it dies/detaches while the session keeps working
    in the `opencode web` server (the "#232 frozen-log" pattern), so a live
    process is NOT the signal. Liveness = the session store (opencode.db — the
    #285 lesson: parts live in the DB, not in a pid): roots are the manager
    "#N IMPL.%" and the architect "IMPL #N %" sessions plus their whole
    parent_id subtree (deeper subagents). True = any of them wrote within
    SESSION_IDLE_LIMIT_S. False = silent longer / no rows (no rows falls back
    to the run-process check). None = session store absent (a host run) — the
    caller must not treat the card as dead."""
    if not SESSION_DB.is_file():
        return None
    try:
        con = sqlite3.connect(f"file:{SESSION_DB}?mode=ro", uri=True)
    except sqlite3.Error:
        return None
    try:
        row = con.execute(
            """WITH RECURSIVE tree(id) AS (
                   SELECT id FROM session WHERE title LIKE ? OR title LIKE ?
                   UNION
                   SELECT s.id FROM session s JOIN tree t ON s.parent_id = t.id
               )
               SELECT MAX(time_updated) FROM session WHERE id IN (SELECT id FROM tree)""",
            (f"#{number} IMPL.%", f"IMPL #{number} %"),
        ).fetchone()
    except sqlite3.Error:
        return None
    finally:
        con.close()
    if not row or row[0] is None:
        # no session rows at all: a just-launched CLI still lives in /proc;
        # an orphaned claim (card claimed, no run ever started) — not alive
        return _impl_run_alive(number)
    idle_s = datetime.now(timezone.utc).timestamp() - row[0] / 1000.0
    return idle_s <= SESSION_IDLE_LIMIT_S


def _closing_pr(number: int) -> tuple[int, str] | None:
    """The merged PR whose body closes the issue (Closes/Fixes/Resolves #N)
    → (pr_number, title), or None. Scans recent merges only — the sweep runs
    every few minutes, the gap it repairs is minutes-to-hours old."""
    r = subprocess.run(
        ["gh", "pr", "list", "--state", "merged", "--limit", "30",
         "--repo", f"{OWNER}/{REPO}", "--json", "number,title,body"],
        capture_output=True, text=True,
    )
    if r.returncode != 0:
        return None
    pat = re.compile(
        rf"(?im)\b(?:close[sd]?|fix(?:e[sd])?|resolve[sd]?)\s*:?\s+(?:{OWNER}/{REPO})?#{number}\b"
    )
    for pr in json.loads(r.stdout or "[]"):
        if pat.search(pr.get("body") or ""):
            return pr["number"], pr.get("title") or ""
    return None


def cmd_reconcile(host_arg: str | None = None, dry_run: bool = False):
    """Watcher-side sweep of stale cards (top of every auto_impl_watch.sh
    loop). Two repairs, both from the 2026-09-22 incident class — a closed or
    dead card left sitting in In IMPL:
      1. issue CLOSED while the card still sits in In IMPL / PR (G7) — the
         finishing flip was lost (e.g. a network flake at the very end of a
         marathon run): flip to In-main (stateReason COMPLETED) or
         "Not planned", and record the "Recently merged" line when the
         closing PR is found. Host-independent — issue state is global truth.
      2. issue OPEN, status In IMPL, host = this machine (or empty), and the
         run's sessions (opencode.db) silent for over SESSION_IDLE_LIMIT_S or
         never started — the dispatch died or wedged without a BLOCKED report
         (e.g. API unreachable at plan-only start, a dead stream): append a
         BLOCKED entry to the auto-impl log (the card then rests for
         CLAIM_TTL_HOURS — crash-loop throttle) and flip back to Ready to IMPL.
    Liveness = session-store freshness (the opencode run CLI is a mere attach
    client and dies while the session keeps working — run processes only fill
    the "no session rows yet" window); run this from the container, where the
    store lives; on a host run (no store) repair 2 is skipped (repair 1 still
    works)."""
    host = _resolve_host(host_arg)
    load_status_field()
    for it in items_with_fields():
        status = (it["status"] or "").lower()
        if not (status.startswith("in impl") or status.startswith("pr")):
            continue
        n = it["number"]
        if it["state"] == "CLOSED":
            target = "In-main"
            r = subprocess.run(
                ["gh", "issue", "view", str(n), "--json", "stateReason",
                 "--repo", f"{OWNER}/{REPO}"],
                capture_output=True, text=True,
            )
            reason = ""
            if r.returncode == 0:
                try:
                    reason = (json.loads(r.stdout) or {}).get("stateReason") or ""
                except ValueError:
                    pass
            if reason and reason != "COMPLETED":
                if "Not planned" not in _status_opts:
                    print(f"warn: #{n} closed as {reason} but the board has no 'Not planned' status — skipped", file=sys.stderr)
                    continue
                target = "Not planned"
            pr = _closing_pr(n)
            desc = (f"#{n}: closed issue in {it['status']} → {target}"
                    + (f" (PR #{pr[0]})" if pr else " (closing PR not found)"))
            if dry_run:
                print(f"would: {desc}")
                continue
            try:
                cmd_status(n, target)
            except SystemExit as e:
                print(f"warn: #{n} flip failed: {e}", file=sys.stderr)
                continue
            if pr:
                try:
                    cmd_merged(n, pr[0], pr[1])
                except SystemExit as e:
                    print(f"warn: #{n} merged line skipped: {e}", file=sys.stderr)
            print(desc)
            continue
        # OPEN + In IMPL: stuck-dispatch repair, own machine (or unowned) only;
        # PR (G7) + OPEN = legitimately on CI — untouched
        if not status.startswith("in impl"):
            continue
        if it["host"] and host and it["host"] != host:
            continue
        fresh = _run_session_fresh(n)
        if fresh is None:
            print("warn: session store not found — stuck-run check skipped (run reconcile from the container)", file=sys.stderr)
            continue
        if fresh:
            continue
        desc = (f"#{n}: In IMPL with sessions silent >{SESSION_IDLE_LIMIT_S // 60}min"
                f" → BLOCKED auto-log entry + Ready to IMPL")
        if dry_run:
            print(f"would: {desc}")
            continue
        # auto-log FIRST: pick-next must never see the card ready without the
        # resting marker (a crash-loop of dead dispatches follows otherwise)
        try:
            cmd_auto_log(n, "BLOCKED reconciler: прогон завис — сессии молчат "
                            "больше часа (или так и не стартовали); карточка "
                            "возвращена в Ready to IMPL, авто-повтор после отдыха")
        except SystemExit as e:
            print(f"warn: #{n} auto-log failed: {e}", file=sys.stderr)
        try:
            cmd_status(n, "Ready to IMPL")
        except SystemExit as e:
            print(f"warn: #{n} flip failed: {e}", file=sys.stderr)
            continue
        print(desc)


def cmd_show(arg: str):
    load_config()
    if arg == "all":
        items = sorted(items_with_fields(), key=lambda it: it["number"])
        if not items:
            print("Board is empty.")
            return
        print(f"{'#':>5}  {'Status':<18} {'Host':<7} {'Gate':<8}  Title")
        for it in items:
            print(f"{it['number']:>5}  {(it['status'] or '-'):<18} {(it['host'] or '-'):<7} {(it['gate'] or '-'):<8}  {it['title']} [{it['state']}]")
        return
    if not arg.isdigit():
        sys.exit("argument must be an issue number or 'all'")
    number = int(arg)
    for it in items_with_fields():
        if it["number"] == number:
            print(f"#{number} [{it['state']}] {it['title']}")
            print(f"  Status: {it['status'] or '-'}")
            print(f"  Host: {it['host'] or '-'}")
            print(f"  Gate: {it['gate'] or '-'}")
            return
    sys.exit(f"#{number} is not on the board. It is added automatically by the first status call.")


def cmd_status(number: int, status: str, host: str | None = None):
    """Move a card's status. Entering In IMPL/In Design also stamps the host
    field (arg > GH_BOARD_HOST > container label file; unresolved → warning,
    field left as is); leaving those statuses clears host AND gate — a card
    that left its phase carries no stale ownership or pending ask.
    Exception (2026-09-21): PR (G7) keeps the host — the card is still owned
    by its machine while on CI (and returns to it if CI is red) — but it
    occupies no IMPL slot (the budget counts only In IMPL status). Leaving
    PR (G7) clears the label."""
    load_status_field()
    if status not in _status_opts:
        sys.exit(f"Unknown status '{status}'. Available: {', '.join(_status_opts)}")
    it = find_item(number)
    set_field(it["item_id"], _status_field_id, _status_opts[status])
    print(f"#{number}: Status → {status}")
    if status.lower().startswith(("in impl", "in design")):
        h = _resolve_host(host)
        if not h:
            print("warn: host not resolved (arg/GH_BOARD_HOST/label file) — host field left unchanged", file=sys.stderr)
        elif h not in _host_field_opts:
            sys.exit(f"Unknown host '{h}'. Field options: {', '.join(_host_field_opts)}")
        else:
            set_field(it["item_id"], _host_field_id, _host_field_opts[h])
            print(f"#{number}: host → {h}")
    elif status.lower().startswith("pr"):
        if it["gate"]:
            set_field(it["item_id"], _gate_field_id, None)
            print(f"#{number}: gate cleared")
    else:
        if it["host"]:
            set_field(it["item_id"], _host_field_id, None)
            print(f"#{number}: host cleared")
        if it["gate"]:
            set_field(it["item_id"], _gate_field_id, None)
            print(f"#{number}: gate cleared")


def cmd_gate(number: int, value: str):
    """Set the card's gate field — the single "this card awaits the user"
    marker: concept|spec|plan = a design gate stop, blocked = an IMPL
    blocker awaiting the user; none = the ask is answered (also cleared
    automatically when the card leaves In IMPL/In Design via cmd_status)."""
    load_status_field()
    it = find_item(number)
    if value == "none":
        set_field(it["item_id"], _gate_field_id, None)
        print(f"#{number}: gate cleared")
        return
    if value not in _gate_field_opts:
        sys.exit(f"Unknown gate '{value}'. Available: {', '.join(_gate_field_opts)}, none")
    set_field(it["item_id"], _gate_field_id, _gate_field_opts[value])
    print(f"#{number}: gate → {value}")


def cmd_issue(number: int):
    """Standard `gh issue view` with fixed output — replaces ad-hoc `--json … -q …` compositions
    (audit 2026-09-09: 33 hand-rolled calls in 3 weeks). Body is capped at 120 lines."""
    load_config()
    r = subprocess.run(
        ["gh", "issue", "view", str(number), "--repo", f"{OWNER}/{REPO}",
         "--json", "number,title,state,labels,body,url"],
        capture_output=True, text=True,
    )
    if r.returncode != 0:
        sys.exit(f"gh issue view error: {r.stderr.strip()}")
    d = json.loads(r.stdout)
    labels = ", ".join(l["name"] for l in d.get("labels") or [])
    print(f"#{d['number']} [{d['state']}] {d['title']}")
    if labels:
        print(f"  Labels: {labels}")
    print(f"  {d['url']}")
    body = (d.get("body") or "").rstrip("\n")
    lines = body.split("\n")
    print()
    print("\n".join(lines[:120]))
    if len(lines) > 120:
        print(f"... [body truncated, {len(lines) - 120} more lines]")


def cmd_merged(number: int, pr: int, title: str = ""):
    """Append "- YYYY-MM-DD #issue [title] → PR #n" to "## Recently merged" (newest first, max 5).

    Scratchpad Discipline v2: the manager runs this at the In-main board flip;
    the session section is then removed. Creates the block (right under the
    file title) when missing.
    """
    if not SCRATCHPAD.exists():
        sys.exit(f"scratchpad not found at {SCRATCHPAD}")
    lines = SCRATCHPAD.read_text(encoding="utf-8").rstrip("\n").split("\n")
    stamp = subprocess.run(["date", "+%F"], capture_output=True, text=True).stdout.strip() \
        or date.today().isoformat()
    entry = f"- {stamp} #{number}" + (f" {title}" if title else "") + f" → PR #{pr}"

    if MERGED_BLOCK in lines:
        head = lines.index(MERGED_BLOCK)
        hard_end = len(lines)
        for i in range(head + 1, len(lines)):
            if lines[i].strip() and not lines[i].startswith("- "):
                hard_end = i
                break
        entries = [ln for ln in lines[head + 1:hard_end] if ln.startswith("- ")]
        if any(f"#{number}" in e and f"PR #{pr}" in e for e in entries):
            print(f"Already recorded: #{number} → PR #{pr}")
            return
        entries = ([entry] + entries)[:MERGED_MAX]
        n_entries = len(entries)
        new = lines[:head] + [MERGED_BLOCK] + entries
        if hard_end < len(lines) and lines[hard_end].strip():
            new.append("")
        new += lines[hard_end:]
    else:
        insert_at = 1 if lines and lines[0].startswith("# ") else 0
        while insert_at < len(lines) and not lines[insert_at].strip():
            insert_at += 1
        new = lines[:insert_at] + [MERGED_BLOCK, entry, ""] + lines[insert_at:]
        n_entries = 1

    SCRATCHPAD.write_text("\n".join(new) + "\n", encoding="utf-8")
    print(f"Recently merged: {entry}")
    print(f"block now holds {n_entries}/{MERGED_MAX} entries")


if __name__ == "__main__":
    args = sys.argv[1:]
    if not args:
        print(__doc__)
        sys.exit(1)
    cmd = args[0]
    if cmd == "pick-next" and len(args) <= 2:
        cmd_pick_next(args[1] if len(args) == 2 else None)
    elif cmd == "pick-next-design":
        cmd_pick_next_design()
    elif cmd == "auto-log" and len(args) == 3:
        cmd_auto_log(int(args[1]), args[2])
    elif cmd == "auto-state" and len(args) == 2:
        cmd_auto_state(int(args[1]))
    elif cmd == "host" and len(args) == 2:
        cmd_host(int(args[1]))
    elif cmd == "reconcile":
        flags = [a for a in args[1:] if a.startswith("--")]
        rest = [a for a in args[1:] if not a.startswith("--")]
        if len(rest) > 1 or any(f != "--dry-run" for f in flags):
            print(__doc__)
            sys.exit(1)
        cmd_reconcile(rest[0] if rest else None, dry_run="--dry-run" in flags)
    elif cmd == "show" and len(args) == 2:
        cmd_show(args[1])
    elif cmd == "status" and len(args) in (3, 4):
        cmd_status(int(args[1]), args[2], args[3] if len(args) == 4 else None)
    elif cmd == "gate" and len(args) == 3:
        cmd_gate(int(args[1]), args[2])
    elif cmd == "merged" and len(args) >= 3:
        cmd_merged(int(args[1]), int(args[2]), " ".join(args[3:]).strip())
    elif cmd == "issue" and len(args) == 2:
        cmd_issue(int(args[1]))
    else:
        print(__doc__)
        sys.exit(1)
